version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6
      
    

    steps:
      - checkout
      - run:
          name: Install dependecies
          command: |
            pwd
            ls -a /home/circleci/project/
            pip3 install -r ../requirements.txt
      - run:
          name: run tests
          command: |
            flake8 --statistics
            pytest -v
